name: Telegram Notify on Stars and Forks

on:
  watch:
    types: [started]
  fork:
    types: [created]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="📢 ${{ github.actor }} just *${{ github.event_name }}* your repo [${{ github.repository }}](https://github.com/${{ github.repository }})!" \
          -d parse_mode=Markdown
